### ISSUE TITLE
Filters on the home page

### ISSUE THREAD

**Issue by pksjce** [SaraVieira/awesome-talks#101]
It would be pretty cool to make a "Advanced search" where we can filter over multiple authors, tags and durations.

I just learned how to filter on the graphiql tool and making the query was really satisfying!
I'd love to work on it if everyone likes the idea. I'd initially put an "Advanced Search" link below the actual search and open a modal where one can filter over a few parameters. We can then enhance the UX if someone with design chops helped

**Comment by SaraVieira** [comment]
That would be incredible !

I would avoid a modal maybe and just put it below the search as a dropdown that only shows when the person clicks on it but we can work on that later :)

❤️

**Comment by SaraVieira** [comment]
closed by https://github.com/SaraVieira/awesome-talks/pull/105

**Comment by pksjce** [comment]
you are awesome!
