### ISSUE TITLE
Bug: order for date pulls results in reverse order

### ISSUE THREAD

**Issue by shaunmolloy** [SaraVieira/awesome-talks#107]
# Bug: order for date pulls results in reverse order

![screen shot 2018-07-27 at 08 57 02](https://user-images.githubusercontent.com/8168925/43309961-2808a170-917e-11e8-8f6d-f59f42abb007.png)

https://en.wikipedia.org/wiki/Sorting#Sorting_information_or_data

![screen shot 2018-07-27 at 09 21 16](https://user-images.githubusercontent.com/8168925/43310063-7964d9bc-917e-11e8-851f-3bda314bd75a.png)

**Comment by SaraVieira** [comment]
Hey !


From what I see when I use order in Year as ASC I start with talks from 2008 and then it keeps going up

Is that wrong ?

**Comment by shaunmolloy** [comment]
> This would show oldest first:
```sql
SELECT *
FROM table
ORDER BY created ASC
LIMIT 10
```

**Comment by SaraVieira** [comment]
That's what is happening if you select by year but the created at is not for the talk but for when it was added into the DB

**Comment by shaunmolloy** [comment]
Ah, so it would probably need adjusting on the frontend, so it's not confusing to the user.

**Comment by SaraVieira** [comment]
That is a good point :(

What should I call it?

**Comment by shaunmolloy** [comment]
"Date added" instead of "created at" might make more sense.

![screen shot 2018-07-27 at 12 51 39](https://user-images.githubusercontent.com/8168925/43319254-ec0b803e-919b-11e8-9896-5ba1234fcb53.png)

**Comment by SaraVieira** [comment]
That date is the video year that I get from youtube :(

**Comment by SaraVieira** [comment]
And I'll change that to date added, that makes more sense :)
