### ISSUE TITLE
deeplinks to video page not working

### ISSUE THREAD

**Issue by jceelen** [SaraVieira/awesome-talks#112]
Expected behaviour: if I copy a link of the videopage like: https://awesometalks.party/video/cjkccx0b21vd30181idvdjstn or share it via twitter the page should show the video as if I navigate from the homepage.

Instead I get a blank screen and the page keeps loading forever... I am not a developer but Google Dev tools says something about provisional headers are shown, maybe that helps? 

![new_tab](https://user-images.githubusercontent.com/2726833/44469822-9bf18700-a628-11e8-9e2a-18b8acd29a27.png)

**Comment by SaraVieira** [comment]
Good catch! I'll dive into this now :)

**Comment by SaraVieira** [comment]
Fixed and deployed! Thank you!
