### ISSUE TITLE
Categories page only render while reloading

### ISSUE THREAD

**Issue by anabellaspinelli** [SaraVieira/awesome-talks#115]
The categories page on the site is not rendering on navigation.

I'm experiencing this issue in Chrome Version 71.0.3578.98 (Official Build) (64-bit) (OSX)

The page is blank when I navigate to it, but then renders for a split second while reloading, and comes back to blank.

Is anyone else experiencing it too?

**Comment by SaraVieira** [comment]
Closed by https://github.com/SaraVieira/awesome-talks/pull/116
