### ISSUE TITLE
Wrong Speaker info for Sarah Drasner

### ISSUE THREAD

**Issue by sdras** [SaraVieira/awesome-talks#117]
Hey! The info on Sarah Drasner is wrong, what is wrong is:

Sarah Drasner is an award-winning Speaker, Head of Developer Experience at Netlify, Vue core team member, and Staff Writer at CSS-Tricks. Sarah is formerly Principal Lead of Emerging Markets, Cloud Advocates at Microsoft and Manager of UX & Engineering at Trulia/Zillow Group. She’s the author of SVG Animations from O’Reilly and has given Frontend Masters workshops. Sarah is a co-organizer of ConcatenateConf, a free conference for Nigerian and Kenyan developers.

You can drop sentences off the end for the length you want! Thanks!

**Comment by SaraVieira** [comment]
Ooops 

I fixed it and I will redeploy that today 

Danke
