### ISSUE TITLE
Cinema mode close bug

### ISSUE THREAD

**Issue by cain** [SaraVieira/awesome-talks#13]
![kapture 2018-05-25 at 12 54 25](https://user-images.githubusercontent.com/15246256/40524371-8fbf1412-601d-11e8-9a10-161b73a356c2.gif)

**Comment by SaraVieira** [comment]
Wow ! That was a weird react youtube bug where it kept rerendering things o.o

I just uploaded a new version with that fixed: https://awesometalks.party/

Let me know if it doesn't fix it :)
