### ISSUE TITLE
Hard to read text in labels 

### ISSUE THREAD

**Issue by vijaybritto** [SaraVieira/awesome-talks#14]
The font color is too light to read. Incredibly hard for people with visual disabilities.
![temp](https://user-images.githubusercontent.com/3725668/40530709-774e2392-6017-11e8-90f2-c4ea09058890.png)
Also, the speakers' names can be arranged in alphabetical order to look up quickly.
Like, 
#A 
Adam
Andrew
#B 
Belle
Baddie
etc.,

**Comment by SaraVieira** [comment]
You are super right about this! I will fix it this morning :)

**Comment by vijaybritto** [comment]
That's great. Looking forward to using this site every day!


________________________________

**Comment by SaraVieira** [comment]
Hey !

Do you like it like this ?

<img width="1257" alt="screen shot 2018-05-25 at 11 19 45" src="https://user-images.githubusercontent.com/1051509/40539722-9455c166-600d-11e8-8fa5-db0b1ede8456.png">

**Comment by vijaybritto** [comment]
This is good enough!
