### ISSUE TITLE
Cinema Mode

### ISSUE THREAD

**Issue by timothyis** [SaraVieira/awesome-talks#2]
Would be amazing if there was some sort of “cinema mode” that made the video expand across the page. I like to binge-watch talks in a separate browser window off to the side. 

Of course, this could be an edge-case since you can just click through to YouTube for their cinema mode. But I'd love to stay on the same site just to watch video after video.

This project is amazing, by the way, I've looked for a way to binge-watch talks for a while!

**Comment by SaraVieira** [comment]
@timothyis You can see the cinema mode here: https://awesometalks.party/

**Comment by timothyis** [comment]
That looks amazing @SaraVieira! Thank you very much 🤩

**Comment by SaraVieira** [comment]
YAAAAY ! You can bookmark that website if you want as that is the final domain 😄 

( .party domains were 90cts :p )

Oh ! You making kap ! It's amazing ! I use it everyday ! Thank you so much for making it 😄 

_closing issue_
