### ISSUE TITLE
Speaker bio

### ISSUE THREAD

**Issue by latentflip** [SaraVieira/awesome-talks#23]
Hey! Thanks for including me, any chance you could update my bio to be "Software Engineer @github" thanks!

**Comment by SaraVieira** [comment]
Hey !

Thanks for making that talk, it was the first time I actually understood the event loop 👍 

So sorry about the mess up, I think I had a hard time finding a bio for you :(

Fixed and updated: https://awesometalks.party/speaker/philip-roberts

**Comment by latentflip** [comment]
No worries, turns out I'm really slow at updating my twitter bio myself!

Thanks!
