### ISSUE TITLE
Add dynamic social media cards

### ISSUE THREAD

**Issue by alexnm** [SaraVieira/awesome-talks#28]
Would be nice to have the speakers page look nice when shared on fb/twitter with the name / photo and maybe description. Not familiar with the Preact ecosystem, is there something like react-helmet to help with this kind of functionality?

**Comment by SaraVieira** [comment]
Good thinking! Anything from the react ecosystem works with preact :) 

So react helmet probably does  👌

**Comment by SaraVieira** [comment]
I added react helmet and it made it worse for some reason when it comes to Twitter o.o

There is a place to test here: https://cards-dev.twitter.com/validator

And a link: https://awesometalks.party/speaker/sarah-drasner

**Comment by alexnm** [comment]
Maybe react-helmet doesn't work 100% with preact? I found this also https://github.com/Download/preact-helmet looks like the same API

From what I see in the sarah's page, the head tags are not updated with react-helmet 
<img width="566" alt="screen shot 2018-05-28 at 10 11 17" src="https://user-images.githubusercontent.com/9945366/40601932-9e35ddde-625f-11e8-8a3e-1e27cddbdab0.png">

**Comment by SaraVieira** [comment]
Fixed by SSR :D
