### ISSUE TITLE
Make separate page for adding a talk 

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/awesome-talks#32]
No one likes modals also this way them bundlesize can get smaller since formik is only loaded there

Also add a why to add this talk and a tags thingy to the form 

Make jazzy submit animation

**Comment by tsiq-swyx** [comment]
interesting, no one likes modals? I'm not a UX expert but i've often felt i prefer modals (feels easier to escape if i accidentally click, for example, and state easily persists if i type something and click away and i come back to it). wonder if theres any research on this topic.

you looking for contributors or do you have this?

**Comment by SaraVieira** [comment]
I'm not either , this was just a thought but in this case you may right actually, if you accidentally click there there goes your search and everything, I can just lazy load the modal itself when it's called

The other ideas was to implement something like https://www.npmjs.com/package/react-dom-confetti on the button when the person submits a talk, inspired by https://twitter.com/joshwcomeau?lang=en talk at react europe and also add two new fields to form, when for adding the tags of the talk and also one for the user to add some notes to the talk and why he loves it, being non mandatory

If you still up for this I will give you access to the API explorer :)

**Comment by SaraVieira** [comment]
This also not a show stopper in any way so take your time doing it and feel free to change anything in the form I have @tsiq-swyx

**Comment by SaraVieira** [comment]
closed as @tsiq-swyx was right about the modal, going to create new issue about the validation

**Comment by tsiq-swyx** [comment]
oh lol i was just discussing :)
