### ISSUE TITLE
Make single video page 

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/awesome-talks#34]
Good for sharing and adding some comments maybe

Link to API: https://api.graphcms.com/simple/v1/awesometalks

Query:

```
{
  Videos(name: "beyond react 16") {
    name
  }
}
```

Replace the id with the name of the current video :)

In react router please create a new route with the name param.
To linkify the name here is the function already used in the speakers page:

```
str.replace(/\s+/g, '-').toLowerCase()
```

and in https://github.com/SaraVieira/awesome-talks/blob/master/src/Pages/Speaker.js you can see how to turn that back to human readable string

Any questions ping me here or on twitter

**Comment by farskid** [comment]
I like this idea. There would also be enough room to expand video player into cinema mode and have a better UX.

**Comment by SaraVieira** [comment]
Exacly! It's also great for speakers to send :)

**Comment by cbh6** [comment]
I think I'll take a look at this. 👍

**Comment by SaraVieira** [comment]
cllosed by https://github.com/SaraVieira/awesome-talks/pull/105
