### ISSUE TITLE
Better Form Validation

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/awesome-talks#35]
In order to have a page for people to vote on talks we need to have better validation on the form, right now it's only required so my idea is:

- Create a new autcomplete input maybe using https://github.com/paypal/downshift and this query to get the tags:

```
  {
    allTagses(orderBy: name_ASC) {
      name
      id
    }
  }
```

and when the person submits we just need to pass the tagID. This is not mandatory

- Have a better validation on the link since I only want the ID of the video so track if people added the whole link and if so add a message maybe saying:
```
Seems you added the whole link, in order for the video to work we only need the ID
```

- Add another field that will be mapped to moderatorNotes on the backend where the person puts why they think the talk is awesome and this will help us choose the talks. This is not mandatory

----
Link to API explorer: https://api.graphcms.com/simple/v1/awesometalks

*Please do not use this create talks that have isPubblished set to true in GraphiQL that*

**Comment by SaraVieira** [comment]
Forgot to mention but I am using Formik, feel free to change that too :)

**Comment by SaraVieira** [comment]
And thank you :)

**Comment by gagyibenedek** [comment]
Here's an alpha version for this: https://github.com/SaraVieira/awesome-talks/pull/57
One more validation step I was thinking about: we could ping the url (www.youtube.com?v=________) to check if it exists.
Also, this solution is pretty optimistic: it just helps with formatting but it won't filter out any jibberish random things they may put there. The only way I can think of that would enforce that is by requiring them to submit a valid url, where the host is youtube.com or youtu.be, but in those who insert only the ID would get an error.
What do you think, which way should we go?

**Comment by SaraVieira** [comment]
Already merged and thank you so much 🎉

I think we should enforce urls now that we can remove the rest, all we really have to do is change the placeholder to be "Insert youtube link".

```
Also, since some of the technologies are new for me, I have a few technical questions about the codebase. Is there a slack channel for awesome-talks where I could ask these questions, or maybe I should just DM you on twitter?
```
Sorry , I didn't see this, you can always ping me on twitter :)

Also adding you to the project as it's easier to iterate over things :)

**Comment by SaraVieira** [comment]
Love the tshirt on your profile pic btw ⚡️

**Comment by sudovijay** [comment]
This seems to be complete now, closing this issue 🙂
