### ISSUE TITLE
Move to Next or After.js

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/awesome-talks#37]
We need server side because of media tags and good deeplinking so ... :(

**Comment by farskid** [comment]
@SaraVieira Let's discuss moving to next.js?

**Comment by SaraVieira** [comment]
I already started the move to after js mainly because I prefer writung my own routes and stuff, you can check out the code in #35

**Comment by tsiq-swyx** [comment]
interesting to watch this project evolve :)

**Comment by cain** [comment]
nuxtjs 😸
