### ISSUE TITLE
[Request For Comments] - Is the shuffling of the talks worth it ?

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/awesome-talks#41]
Yellow Everyone !

SO I have been trying to move this to a server side rendered app for SEO, performance reasons and also so I can get a server to cache the requests in the future and the biggest issue I have been having is the shuffle of the talks because that has to be done when the data arrives and then all I can do is lazy load things but I can't really apply pagination :(

My question here is: Is it worth it ? Should I remove this and have normal pagination ?

@pksjce @varjmes @farskid @tsiq-swyx @gagyibenedek 

Anyone I didn't tag is welcome to leave their opnion :D

**Comment by tsiq-swyx** [comment]
i am having deja vu because i swear i have come across this exact issue before with some other popular site. i would say to remove it. seo/perf more important.

now if only you had react suspense SSR :)

**Comment by farskid** [comment]
I'd say we can skip it for now and do the pagination on the client side. SSR has more priority than caching the video request IMO.
But we might wanna have it in mind that it's probably needed to be considered in the future.

**Comment by cain** [comment]
Vote to remove. Exactly what @pksjce said 😄

**Comment by gagyibenedek** [comment]
I'm not a fan of the shuffling, so I'm totally fine with letting it go.
I'm not sure I understand what's the technical difficulty tho. At some point, before the actual rendering is done on the server side, you have a list of talks that need to be handled. Can't you apply the shuffle algorithm on that list, on server side?

(hey @pksjce, it's nice running into you here :) )

**Comment by SaraVieira** [comment]
The problem is I get the talks and then shuffle them on the server or the client and after that I need something to lazy load the ones not shown and the lazy loading believes there is a window height and there is not on the server so it just doesn't show anything untill we get to the client

This also means that I can't do the pagination on the server because to shuffle them I need all the talks and not just 10 of them per page


I will then remove that in favor of having some sweet server pagination 

Thank you all!

**Comment by varjmes** [comment]
BANISH!

**Comment by SaraVieira** [comment]
closed by #37
