### ISSUE TITLE
Show video length

### ISSUE THREAD

**Issue by dan2k3k4** [SaraVieira/awesome-talks#43]
We tend to sync together to watch frontend related conference talks over lunch, so being able to see how long each video is without having to click to play each video would be helpful to know which videos we can watch given only a certain about of time left at lunch.

**Comment by SaraVieira** [comment]
Hey !

This is a GREAT idea so I started hacking away at it and I think I got a pretty solid implementation at https://github.com/SaraVieira/awesome-talks/pull/44

You can see the demo here: https://5b0d69eadd6a540f7d24c206--peaceful-banach-108bd4.netlify.com/

What do you think ?

**Comment by tsiq-swyx** [comment]
looks great. in fact its so impt a bing style filter (<20min, 20-60min,
60+++) might be helpful for this exact use case. the TED website does this
too

**Comment by SaraVieira** [comment]
It's very helpful ! Once this is merged I will work on that filter and also an order by duration :)

**Comment by dan2k3k4** [comment]
Hey @SaraVieira, looks great so far, although I think the bold on `Duration:` draws people's attention a little too much - and then you don't really notice the tags anymore.

Do we need the state `Duration:` or would just showing `55min`, `1hr 13min` work?

Also, if we're going with full `hour` and `minute` then `2 hour and 4 minutes` should be `2 hours and 4 minutes` :)

**Comment by SaraVieira** [comment]
Both of your ideas may be better because I have no idea how to make things plurar in moment :(

I'll be flying to Amsterdam today morning but I'll get to this in the afternoon :)
