### ISSUE TITLE
[Request] Search Filter In Speakers Page

### ISSUE THREAD

**Issue by sudovijay** [SaraVieira/awesome-talks#49]
As you listing all speakers at once and its a long list so adding a live filter search can help in looking for someone up easily .. even you can also cache that api.graphcms.com response for a while may be,

**Comment by SaraVieira** [comment]
Adding this now :)

**Comment by SaraVieira** [comment]
Closed by https://github.com/SaraVieira/awesome-talks/commit/f9e66b668505495c00b467ef662997c62939088c
