### ISSUE TITLE
[Caching] Need to cache stuff

### ISSUE THREAD

**Issue by sudovijay** [SaraVieira/awesome-talks#52]
As i did notice its a PWA but it doesn't cache graphcms.com requests so all one could see in offline mode is this

> Error!: Error: Network error: Failed to fetch

even an average requests to graphcms takes about 1.5 seconds and 100kb ( 33kb gzipped ) data to load so when the user refreshes the page it shows that preloader every single time, why not cache it for a while,

**Comment by SaraVieira** [comment]
I have removed the PWA but it will be added again and I am now working on the server to cache the requests to graphcms for about an hour and clean that every hour.

I can't go over the call limit ahah

**Comment by sudovijay** [comment]
why just an hour? than you need to run a cron to clear that every hour , why bother doing all that? you could clear cache when you approve a new video in the list or add new speaker basically do any change. how about that?

**Comment by SaraVieira** [comment]
So I should add an endpoint that just clears the cache? Does that sound like a good idea?

**Comment by sudovijay** [comment]
yep kind of calling a hook may be which clears the cache for ya 🙂

**Comment by SaraVieira** [comment]
Closed as not PWA anymore and cache is on
