### ISSUE TITLE
Videos listed like Netflix!

### ISSUE THREAD

**Issue by pksjce** [SaraVieira/awesome-talks#6]
I love this project and have been wanting such a thing for years! I think it has great potential to be the one stop place to search and find tech talks.
I would love it if it were designed like Netflix. 
We could start with the categories page to experiment and then if its a success, apply it to the rest of the site. 
Each tag could be lined so
![netflix-categories](https://user-images.githubusercontent.com/417268/40483194-7f37243c-5f9a-11e8-9050-2b0910a536f8.png)

We would need a solid slider implementation. I'm experimenting with https://github.com/Noojuno/preact-slick. The examples look solid. 

I need help with lazy loading Tags query like the ALL_VIDEOS query. I'm not that  handy with gql queries. Will try to get a PR this weekend. What do you think?

**Comment by SaraVieira** [comment]
Yellow !!

This is a great idea we can do with the categories page to start ! Sounds amazing !

Don't worry about the lazy loading I can help you with that when we got that PR.

Thank you so much for the idea and I would love to see this implemented :D

**Comment by SaraVieira** [comment]
Hey !

@pksjce Should I close this issue ? Do you still want to implement this ? :)

**Comment by pksjce** [comment]
I'm foolishly building my own carousel, this is a great real world example for me to use. It might take some time though. I'm not somebody who codes a lot out of office. So, its really upto you. But I honestly browsing videos and shopping items are legit use cases for carousels and done right they can be sooo good.

**Comment by cain** [comment]
I might give this a crack next week 😃

**Comment by SaraVieira** [comment]
Oh noes, if it's still a good idea it will stay open 👌

I'll just add some tags :)

@cain let me know if you need help :)
