### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by cain** [SaraVieira/awesome-talks#60]
Hello people.

I had some spare time, so i decided to have a look for a new design. I may have gone a bit crazy on the emoji's but would love some feedback!
![design test](https://user-images.githubusercontent.com/15246256/40819529-eb8a51ae-659e-11e8-9116-60dff7c8630c.png)

@pksjce @SaraVieira @farskid @tsiq-swyx @SaraVieira @varjmes @glennreyes @hosmelq

**Comment by sudovijay** [comment]
it look similar , just few changes here & there, its better to implement them here if needed just saying 🙂

**Comment by SaraVieira** [comment]
I'm going to ping @siddharthkp because he wants some design improvements here :)

I ❤️ the nav and the tags!

There is also a logo for the logo so we should work. On that thogheter 😍

Can you put that on Figma so we can all collaborate? :)

**Comment by siddharthkp** [comment]
Love it!

I'm all over it 😄

**Comment by hosmelq** [comment]
Amazing, I like the nav and the new position of the author's name ♥️

**Comment by cain** [comment]
https://www.figma.com/file/Qm18JEjdYsYGo721cUXAoJJg/Awesometalks-design send me emails for permissions 😄

**Comment by SaraVieira** [comment]
Hey@iamsaravieira.com :)

**Comment by hosmelq** [comment]
hosmelq@gmail.com

**Comment by siddharthkp** [comment]
siddharth.kshetrapal@gmail.com

**Comment by cain** [comment]
Done

**Comment by pksjce** [comment]
I love the positioning of the speaker name. Such a small effective change!

**Comment by sudovijay** [comment]
did a minor change in design for now , based on comments.  In PR #65  commit 565ce35bad6f196901dc49ed6b703269c8130f35 , until you guys finalize something, just to let you know im no designer so lemme know how you feel about it, will revert the commit otherwise.

**Comment by cain** [comment]
@SaraVieira @siddharthkp Whats the go with the design?

Yes, No? Anyone working on it besides https://github.com/SaraVieira/awesome-talks/commit/565ce35bad6f196901dc49ed6b703269c8130f35 ?

**Comment by hosmelq** [comment]
I can help with this one if the current design stays.

**Comment by siddharthkp** [comment]
Looks really good! I'm going to work on it in super slow motion 😅

Feel free to jump ahead and start implementing stuff

**Comment by cain** [comment]
@siddharthkp Want to set up a feature branch we can work on?

**Comment by siddharthkp** [comment]
https://github.com/SaraVieira/awesome-talks/tree/redesign

**Comment by cain** [comment]
@SaraVieira can you add me as a collaborator to push to this branch? 😃

**Comment by SaraVieira** [comment]
Of course! Done! 🎉

**Comment by hosmelq** [comment]
@cain are you working on this ?

**Comment by cain** [comment]
Don't have time at the moment. Go ahead if you'd like!

**Comment by gsimone** [comment]
I'd be happy to give it a go this weekend, do you have a source (sketch, w/e) for the new design?

**Comment by SaraVieira** [comment]
@gsimone there is a figma file we can share if you give us your email :)

**Comment by gsimone** [comment]
Sure, gianmarcosimone89@gmail.com

**Comment by SaraVieira** [comment]
@cain Can you invite him ? :)

**Comment by cain** [comment]
@SaraVieira @gsimone I've started working with this design. I'll push my code to the feature branch that was made soon :)

**Comment by SaraVieira** [comment]
@cain Awesome ! Thank you :D
