### ISSUE TITLE
Wrong Speaker info for  Zeynep Tufekci

### ISSUE THREAD

**Issue by teddy-error** [SaraVieira/awesome-talks#66]
Hey! [The info on  **Zeynep Tufekci**](https://awesometalks.party/speaker/-zeynep-tufekci) is wrong, what is wrong is:
She is incorrectly cited on **Alex Qin**'s talk [Shaving My Head Made Me a Better Programmer](https://www.youtube.com/watch?v=jJFuAce9mZU)

**Comment by SaraVieira** [comment]
Dang....

**Comment by SaraVieira** [comment]
I'mma fix it!

**Comment by SaraVieira** [comment]
Fixed it! It should be a while before it gets to the app tho
