### ISSUE TITLE
Add sorting

### ISSUE THREAD

**Issue by douglance** [SaraVieira/awesome-talks#68]
Sort by popularity would be nice.

**Comment by SaraVieira** [comment]
Would by YouTube views work?

**Comment by sudovijay** [comment]
it'll be like comparing talks / them lol some peeps can get offended  idk, anyway we could do that by fav count (need to store that too) or by views ( like times a video viewed till end),  but that'll make things complicated, 

could do by youtube views which we already have via api , that'll be easy to implement too

**Comment by SaraVieira** [comment]
I think the problem. We could have with YouTube views is that Ted vídeos would always come first and that is not necessarily what we want :(

**Comment by sudovijay** [comment]
yep, sorting via fav count is much better way i quess, but there are quite a things that need to be taken care of like unique user ip , anyone can spam fav count as we storing them locally by using multiple sessions or by clearing localStorage <favorites__awesome-talks> & storing IPs with fav count  just not worth it for such website, We could do csrf token based validation though that compares provided token with session token and then store fav count.

**Comment by SaraVieira** [comment]
So, the first step to making this is add a liked property on the backend that will increase when someone likes a video, so it will be stored in localstorage for that user and also in the CMS, I can start by adding that and after that the sort by popularity can be a combination of both, YouTube views count like 30% and the likes count like 70% so this way we can make it as soon as possible even if there are not a lot of videos with likes on the CMS

**Comment by sudovijay** [comment]
people can clear localStorage & even fake likes if they wanted to, we need to do something for that but lets not think about that now,  one thing at a time,  Combination of both youtube views count and likes count sounds great to me,

**Comment by SaraVieira** [comment]
closed by https://github.com/SaraVieira/awesome-talks/pull/105
