### ISSUE TITLE
Duplicate submissions result in uncaught GraphQL exception

### ISSUE THREAD

**Issue by teddy-error** [SaraVieira/awesome-talks#69]
Error: `GraphQL error: A unique constraint would be violated on Videos`

Expected behavior:
GraphQL error is caught and handled by toggling an error message to the user

**Comment by SaraVieira** [comment]
Hey!

Sorry for that! There is already a PR to show the user an error :)

I'll close when the PR is merged :)

**Comment by sudovijay** [comment]
All errors catched, b01b6bd74ab0064bf2ff77887fb4dd389aa624a3 you can close the issue

**Comment by SaraVieira** [comment]
closed by #65
