### ISSUE TITLE
Why shuffled talks?

### ISSUE THREAD

**Issue by rahuldhawani** [SaraVieira/awesome-talks#7]
Superb knowledge source!!!

Was wondering, is there any reason why the talks are [shuffled](https://github.com/SaraVieira/awesome-talks/blob/master/src/Components/Talks.js#L18) on the homepage?

Opened your tweet, Sandi Metz talk was on top, opened the link on the laptop, boom, no more Sandi Metz talk on top 😢 

PS: Any tasks to contribute to this project? Would love to help.

**Comment by SaraVieira** [comment]
Hey!

Thanks :)

I did it so you wouldn't keep seeing the same talks over and over again

Do you think it would make sense to remove it?

Do you have anything you would like to add? :)

**Comment by rahuldhawani** [comment]
Well, I guess, once the [search](https://github.com/SaraVieira/awesome-talks/issues/1) comes into the picture, shuffle will make sense. 

Was the thought process to binge watch talks? In that case, it would make sense shuffle is great. 

Things I would like to be added:
1) Search (I guess, it's being built already)
2) A "Propose a talk" page. As the theme of the Awesome Talks is curated talks, let people propose a talk, and other people can vote on it if they find it "Awesome" enough. 
But not sure people will vote or not. Your thoughts on this?

**Comment by farskid** [comment]
@rahuldhawani 
Search is now merged and built into the website https://github.com/SaraVieira/awesome-talks/pull/30
I'm not sure about the deployment process though.

About the proposal feature, I'd say it's a bit overkill to ask for votes from people since the project is rather young. Would it make sense to let all the videos, be added to the list and instead offer a *report as not awesome enough* thingy?

**Comment by SaraVieira** [comment]
This is a great idea! It will force me to make some validation for the form and make it in another page and that is already and issue I created so by validating the ID the person passes this is super doable :)

**Comment by gagyibenedek** [comment]
Write a spec for the validation in a different issue, and I may be able to jump in with a PR :)

**Comment by gagyibenedek** [comment]
Omg, it's too early for me to read :O So yeah, a PR may arrive for the other issue :)

**Comment by SaraVieira** [comment]
I'm creating the other issue now :)

**Comment by SaraVieira** [comment]
@gagyibenedek  https://github.com/SaraVieira/awesome-talks/issues/35

**Comment by SaraVieira** [comment]
Closing as I am creating an issue for the form validation and one for the propose a talk page 👌
