### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by sudovijay** [SaraVieira/awesome-talks#70]
hey, just saw your last commit , 60b2922c6268d7d624201ed90e01b0fad9e18243 , i noticed you did removed these opts  from Player component which we passed , having controls is ok ( the point is moot) but you sure you want related videos?
`
host: 'https://www.youtube-nocookie.com',	
                        playerVars: {	
                            rel: 0,	
                            showinfo: 0	
                       }
`

**Comment by SaraVieira** [comment]
That was a mistake! I gotta put the back!!!

**Comment by sudovijay** [comment]
lol you sure? okay adding 'em back,  enjoy the weekend 🙂

**Comment by SaraVieira** [comment]
But let the controls stay please, it's way easier to work that way :)

Thank you and have a great weekend!
