### ISSUE TITLE
Binge Watch!  📺

### ISSUE THREAD

**Issue by sudovijay** [SaraVieira/awesome-talks#71]
Right now when a user end watching a video it get added in its watched list which is cool but why not we take it a step further like autoplaying similar videos probably by same speaker, same category or even similar to title (whichever available) , it'll be great to have this and i quess easy to implement too,

**Comment by SaraVieira** [comment]
This would be amazing! If you are on cinema mode just show related videos and play those in there!

Just need a simple related algorithm, I don't think it will be too hard too!
