### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by dimitarnestorov** [SaraVieira/awesome-talks#81]
A picture is worth 1000 words:
![image](https://user-images.githubusercontent.com/8790386/40969769-72a41f06-68c1-11e8-8f54-76dc8eaccb9d.png)

**Comment by SaraVieira** [comment]
Oh dang, gotta get that overflow ellipsis

**Comment by sudovijay** [comment]
Already cutting the string above the length 60, so i quess this is a better fix ef4d011a2c96d2145248d1c6f1dcd4562802f7a2 , closing this issue 🙂
