### ISSUE TITLE
Video thumbnail image size

### ISSUE THREAD

**Issue by cain** [SaraVieira/awesome-talks#86]
<img width="300" alt="screen shot 2018-06-06 at 10 56 36 am" src="https://user-images.githubusercontent.com/15246256/41010315-f50e552a-6979-11e8-991d-33ac91fddda4.png">

Image thumbnails look pretty bad on retina screens due to the size. And it looks like all the other resolutions youtube provide dont really work with our 3 column layout.

Thoughts on a 4 column layout instead? 
<img width="400" alt="screen shot 2018-06-06 at 11 08 34 am" src="https://user-images.githubusercontent.com/15246256/41010367-4c9116de-697a-11e8-87fc-80a9b6fa5ba8.png">

**Comment by sudovijay** [comment]
we could implement something like `srcset` here, anyway @cain  did you tried other reso. that youtube provide
 
`https://img.youtube.com/vi/NAimzL6XXAY/mqdefault.jpg
https://img.youtube.com/vi/NAimzL6XXAY/hqdefault.jpg
https://img.youtube.com/vi/NAimzL6XXAY/maxresdefault.jpg`

the one with `maxres` should look fine i quess.

**Comment by SaraVieira** [comment]
Fixed by https://github.com/SaraVieira/awesome-talks/commit/31273f98a8fc6631caf210a37d82d25e65d97afb

Four column layout would make it to squished , I would rather go for a two column layout

**Comment by sudovijay** [comment]
lets close this for now,  three column layout seems perfect too me 🙂
