### ISSUE TITLE
Lets have some cookies 🍪

### ISSUE THREAD

**Issue by sudovijay** [SaraVieira/awesome-talks#88]
As we doing SSR and storing favs and watched videos in localStorage, There's no way we can access that on server level so right now neither of them seems to be working as they are kinda limited with session more or less.
One way to do is re render few stuff at client side when the app actually get mounted
Even the dark mode fall to default as we ain't storing the state anywhere

Other way is to have `cookies`, though they have this limit of `4k (4096 bytes)` but i quess that'll be enough for our purpose. Cookies are perfect for dark mode too

On server side we can either parse cookies with node or use express with cookies parser middleware to parse cookies from request and use that for our purpose.

And, who doesn't like cookies, anyway?

**Comment by sudovijay** [comment]
>  I'm super okay with this but I don't have the experience to do this
Now thats weird, the Great @SaraVieira don't have experience with cookies, i thought she like cookies too .. 
Well, i'll try to do this tonight, tbh there's no way we could achieve this without cookies as we doing SSR. I mean we could do something like storing user ip & settings in server but that'll be too much stuff tbh , and yes we have to add that warning thing, Thanks to EU Cookie Law 🇪🇺

**Comment by SaraVieira** [comment]
I like to consume them, not create them :p . 

Here are is a package for the law:
https://github.com/buildo/react-cookie-banner 

Just saw that we use cookies for favorites, watched and also check if you like dark mode and saw this banner already ahah

**Comment by sudovijay** [comment]
done in #89, Closing now .
