### ISSUE TITLE
Wrong Speaker info for Luke Bonaccorsi

### ISSUE THREAD

**Issue by lukeb-uk** [SaraVieira/awesome-talks#90]
The twitter link for my page is messed up, it has the twitter URL in there twice and currently links to `https://twitter.com/https://twitter.com/lukeb_uk`

**Comment by sudovijay** [comment]
Yep. stored the full url instead of username 🙂 , thanks @lukeb-uk , just another mistake

**Comment by SaraVieira** [comment]
Hey !

I'm so sorry @lukeb-uk ! Turns out I did that to a bunch of people including myself :(

It has been fixed and should be updated on the website this afternoon

**Comment by lukeb-uk** [comment]
🎉 Thank you @SaraVieira, and thank you for such a great site!
