### ISSUE TITLE
Wrong Speaker info for Alan Kay

### ISSUE THREAD

**Issue by alanone1** [SaraVieira/awesome-talks#94]
Hey! The info on Alan Kay is wrong, what is wrong is you are showing the "Fry the Monkeys" Alan Kay instead of the Computer Science Turing Award Alan Kay (check out the very different likenesses, etc.(

**Comment by pksjce** [comment]
Oh god! You are right. I fixed it on graphcms. @SaraVieira - This doesnt seem to take effect on the website. But I saw on my local that it was fetching the right data. Does it require a restart of the app server?

**Comment by SaraVieira** [comment]
Oh shit ! I will deploy a new version this afternoon :)

**Comment by alanone1** [comment]
No problem with me at all ... there are lots of "Alan Kay"s -- a judge, a classical clarinet player, a management consultant, a professional wrestler, a survivalist, etc. Probably an ax murderer (the law of large numbers, etc.)

But the one who did the two talks c'est moi.
Cheers
Alan

**Comment by SaraVieira** [comment]
Again so sorry, and sorry you created the GH profile for this, it has been fixed: https://awesometalks.party/speaker/alan-kay


Thank you for being understanding
